# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sishin <sishin@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/30 15:11:05 by sishin            #+#    #+#              #
#    Updated: 2023/03/30 22:40:44 by sishin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	=	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c\
			ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c\
			ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c\
			ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c\
			ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c\
			ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

SRCS_BO	=	ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c\
			ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c\
			ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

OBJS	=	${SRCS:.c=.o}

OBJS_BO	=	${OBJS} ${SRCS_BO:.c=.o}

CC		=	cc

CFLAGS	=	-Wall -Wextra -Werror

NAME	=	libft.a

all		:	${NAME}

%.o		:	%.c
			${CC} ${CFLAGS} -c $< -o $@

${NAME} :	${OBJS}
			rm -f all bonus ${NAME}
			ar -rc ${NAME} ${OBJS}
			touch all

bonus	:	${OBJS_BO}
			rm -f all bonus ${NAME}
			ar -rc ${NAME} ${OBJS_BO}
			touch bonus

clean	:
			rm -f ${OBJS_BO} all bonus

fclean	:	clean
			rm -f ${NAME}

re		:	fclean all

.PHONY	:	all clean fclean re .c.o
